name: Nas-tools Build Docker Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - requirements.txt
      - docker/Dockerfile
      - docker/entrypoint.sh
      - version.py
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Release version
        id: release_version
        run: |
          app_version=$(cat version.py |sed -ne "s/APP_VERSION\s=\s'\(.*\)'/\1/gp")
          echo "app_version=$app_version" >> $GITHUB_ENV      
      - 
        name: Buildx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:${{ env.app_version }}
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:latest
